### ISSUE TITLE
Need to create an option to add head scripts for Non-Amp.

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/ads-for-wp#111]
Need to create an option to add head scripts for Non-Amp.
Ref : https://secure.helpscout.net/conversation/694561561/38613?folderId=2322652
Ref : https://support.google.com/admanager/answer/1638622?hl=en

**Comment by Sanjeevsetu** [comment]
This ticket is about doubleclick ad support which we have implemented.
