### ISSUE TITLE
Need to push an urgent update #242

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/ads-for-wp#179]
regarding this ticket: ahmedkaludi/accelerated-mobile-pages#3055. Debug error in control-center.php file.

**Comment by ahmedkaludi** [comment]
- [ ] and a debug error: [04-May-2019 10:09:30 UTC] PHP Warning: array_key_exists () expects parameter 2 to be array, string given in /home/josemisa/public_html/Deportesaludable.com/wp-content/plugins/ads-for- wp / output / functions.php on line 509

https://wordpress.org/support/topic/error-log-63/#post-11496525
