### ISSUE TITLE
Add sticky Ads Feature with Ad Type Double Click

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/ads-for-wp#183]
Screenshot: https://monosnap.com/file/RNVtwtghscOVqlS3JHlgx6GSJux0VI

**Comment by ahmedkaludi** [comment]
Same as https://github.com/ahmedkaludi/ads-for-wp/issues/174

**Comment by santosh8793** [comment]
This is issue has been fixed in below ticket
Ticket Ref: https://github.com/ahmedkaludi/ads-for-wp/issues/174
