### ISSUE TITLE
Duplicate Queries

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/ads-for-wp#194]
adsforwp_output_functions->adsforwp_display_ads. 10 calls

https://prnt.sc/nw79yv
https://prnt.sc/nw8bco

**Comment by akashagrjsr** [comment]
SELECT wp_bsaqk052jw_posts.*
FROM wp_bsaqk052jw_posts 
WHERE 1=1 
AND wp_bsaqk052jw_posts.post_type = 'adsforwp-groups'
AND ((wp_bsaqk052jw_posts.post_status = 'publish')) 
ORDER BY wp_bsaqk052jw_posts.post_date DESC

get_template_part('content','')
wp-includes/general-template.php:168
locate_template()
wp-includes/template.php:671
load_template('wp-content/themes/baskerville/content.php')
wp-includes/template.php:724
the_excerpt()
wp-includes/post-template.php:401
get_the_excerpt()
wp-includes/post-template.php:436
apply_filters('get_the_excerpt')
wp-includes/plugin.php:208
wp_trim_excerpt()
wp-includes/formatting.php:3705
apply_filters('the_content')
wp-includes/plugin.php:208
adsforwp_output_functions->adsforwp_display_ads()
wp-content/plugins/ads-for-wp/output/functions.php:928
adsforwp_admin_common_functions->adsforwp_check_ads_in_group()
wp-content/plugins/ads-for-wp/admin/common-functions.php:1302
adsforwp_admin_common_functions->adsforwp_fetch_all_groups()
wp-content/plugins/ads-for-wp/admin/common-functions.php:1267
get_posts()
wp-includes/post.php:1961
WP_Query->query()
wp-includes/class-wp-query.php:3404
WP_Query->get_posts()
wp-includes/class-wp-query.php:2996
