### ISSUE TITLE
Security issue reported by wordpress

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/ads-for-wp#206]

**Comment by MohammedKaludi** [comment]
Escaping : 
1) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L306 
2) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L338
3) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L350
4) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L370
5) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L378 
and Similar instances in this page

**Comment by MohammedKaludi** [comment]
Do not use inline js

https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics-settings.php#L431

**Comment by MohammedKaludi** [comment]
Escaping
1) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics.php#L90
2) https://github.com/ahmedkaludi/ads-for-wp/blob/master/admin/analytics.php#L114
3) Add nonce https://github.com/ahmedkaludi/ads-for-wp/blob/1.9/admin/common-functions.php#L86
4) Permission and nonce both missing https://github.com/ahmedkaludi/ads-for-wp/blob/1.9/admin/control-center.php#L34 and escaping is missing.
5) Remove inline scripts https://github.com/ahmedkaludi/ads-for-wp/blob/1.9/admin/control-center.php#L1195

**Comment by Sanjeevsetu** [comment]
#L90 and #L114. :  esc_url removes the charactor "${" which we need in this url and this is a static url so we can leave it or suggest.

#L34 : this function is being called on hooks add_action('admin_init', array($this, 'adsforwp_import_all_settings'),9);. we have setup the permission. for the nonce suggeest.
