### ISSUE TITLE
Need to add a notice below the User targeting section, only for the Device Type

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#210]
The reason for this is because a caching plugin is caching the mobile and desktop as same, so it's not giving the proper result, in this case, user was using the WP Rocket plugin.

So we should give a notice, which will also contain a documentation link to get more help.

REF: https://secure.helpscout.net/conversation/897519703/73005/
documentation request raised: https://trello.com/c/E7A9yQ4v/406-my-user-targetting-is-not-working-when-targetting-the-ad-on-the-mobile-and-desktop-how-do-i-fix-this

**Comment by santosh8793** [comment]
Pushed in 1.9.11
