### ISSUE TITLE
In Custom ads the custom code is not getting added

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/ads-for-wp#211]
When the user add code for custom ads in the custom ads section after updating the code is not getting stored and it's showing blank.

Ref:  https://secure.helpscout.net/conversation/897494150/72996?folderId=3081347
Screenshort: https://prnt.sc/ocjo12

**Comment by ahmedkaludi** [comment]
I think this is fixed, right? we can close it? test it please
