### ISSUE TITLE
floating ads

### ISSUE THREAD

**Issue by iamkingsleyf** [ahmedkaludi/ads-for-wp#217]
Hi,

How do i set a mobile banner of 320x50/100 on mobile devices? i use your PWA plugin.

Regards

**Comment by ahmedkaludi** [comment]
Can you please explain this issue a little more?

**Comment by iamkingsleyf** [comment]
At the bottom of http://imgur.com/gallery/KP3gsHi you see a floating AD, just like adsense auto ads appearing at the top of the page.

How do i do this for mobile and pc?

**Comment by ahmedkaludi** [comment]
Those are called Sticky ads in AMP, but it's confusing to add it in Non-AMP because google doesn't provide enough data for that.
