### ISSUE TITLE
Need to add compatibility of Mediavine in ADS FOR WP

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/ads-for-wp#220]
Helpscout link: https://secure.helpscout.net/conversation/902653916/73698?folderId=2770545

Need to implement Mediavine support in AMP and NON-AMP.

**Comment by ahmedkaludi** [comment]
- [ ] feature

- [ ] tutorial

**Comment by santosh8793** [comment]
Pushed in 1.9.6
