### ISSUE TITLE
Last User Targeting and Advance Display option is not deleting

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/ads-for-wp#222]
Last User Targeting and Advance Display option is not deleting 

Ref:  https://secure.helpscout.net/conversation/903941141/74045?folderId=3081347

Screenshot: https://monosnap.com/file/GH1v1grH7fdk1TAQLkqW53NOOadwJE

**Comment by santosh8793** [comment]
Pushed in 1.9.4
