### ISSUE TITLE
Need to Add the optional option to place the ad in the paragraph based on percentage.

### ISSUE THREAD

**Issue by sushmarachakonda** [ahmedkaludi/ads-for-wp#223]
need something to place ads at 30%, 50%, 70% and 90% of <p> tag within my content (when the content of the paragraph is lengthy and has a number of paragraphs)

https://secure.helpscout.net/conversation/893365069/72422?folderId=3004564

**Comment by iamkingsleyf** [comment]
Nice, i like this and also after X number of paragraphs (which already exists)

**Comment by santosh8793** [comment]
Pushed in 1.9.11
