### ISSUE TITLE
Code Stripped of from Custom ad section

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#227]
try this: 

`<amp-ad width="600" height="600" layout="responsive" type="mgid" data-publisher="**********" data-widget="******" data-container="******ScriptRoot******" ></amp-ad>`

https://wordpress.org/support/topic/custom-code-being-stripped-off/

**Comment by santosh8793** [comment]
Pushed in 1.9.4

**Comment by encodia** [comment]
Hi there,

I am using 1.9.6

`<amp-ad width="300" height="169" type="viralize" layout="responsive" data-zid="xxx"></amp-ad>`

You strip away from "viralize"

<amp-ad width="300" height="250" type="doubleclick" data-slot="/123456789/STRING/STRING_AMP" rtc-config="{ 'vendors': { 'criteo': {'NETWORK_ID': 6988} , 'indexexchange': {'SITE_ID': 123456} }, 'timeoutMillis': 1000}"></amp-ad>

You strip away all rtc-config

Thank you

**Comment by encodia** [comment]
I temporary fixed "my" issue:

`$my_allowed['amp-ad'] = array(
                    'class'                     => array(),
                    'width'                     => array(),
                    'height'                    => array(),
                    'type'                      => array(),
                    'data-slot'                 => array(),
                    'data-ad-client'            => array(),
                    'data-ad-slot'              => array(),
                    'data-tagtype'              => array(),
                    'data-cid'                  => array(),
                    'data-crid'                 => array(),
                    'data-mid'                  => array(),
                    'data-block-id'             => array(),
                    'data-html-access-allowed'  => array(),
                    'data-property'             => array(),
                    'data-zone'                 => array(),
                    'data-json'                 => array(),
                    'fallback'                  => array(),
                    **'rtc-config'                => array(),
                    'data-zid'                  => array(),
                    'layout'                    => array(),**
            );`
