### ISSUE TITLE
User wants to get the text to wrap around the ads 

### ISSUE THREAD

**Issue by keshavsharma333** [ahmedkaludi/ads-for-wp#234]
Text should surround the ads and no empty space should be left around the ads.
Ref: https://secure.helpscout.net/conversation/940792315/79436?folderId=3044500

**Comment by keshavsharma333** [comment]
Tested on localhost. The ad aligns itself to the left or right but doesn't allow text around it. need to do text-align: float

**Comment by santosh8793** [comment]
Pushed in 1.9.5
