### ISSUE TITLE
AMP ads are not in center on pc

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/ads-for-wp#236]
Ref: https://secure.helpscout.net/conversation/944946867/79970?folderId=3081347

![AMP ADS ON PC BY USING ADS FOR AMP PLUGIN](https://user-images.githubusercontent.com/44563327/64344676-8f11bc80-d00c-11e9-9483-1e0077da00c4.jpg)
![AMP ADS PROBLEM ON PC NOT IN CENTER AND HALF AD IS NOT VISIBLE LIKE TEXT](https://user-images.githubusercontent.com/44563327/64344678-8f11bc80-d00c-11e9-8687-2d4ad9789417.jpg)

**Comment by santosh8793** [comment]
Due to inline style(margin-left) which is getting added by the google ads, the display of ads with center alignment was not possible.
