### ISSUE TITLE
Ad block support not working 

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/ads-for-wp#237]
Ad-block support not working with this AdBlock google chrome extension

Ref: https://secure.helpscout.net/conversation/944946867/79970?folderId=3081347

![ADBLOCK](https://user-images.githubusercontent.com/44563327/64344744-b072a880-d00c-11e9-84bf-48f49ae9a153.jpg)

**Comment by santosh8793** [comment]
It is not possible to show ads when AdBlocker is enabled but we are creating new featured in this below ticket.
Ref: https://github.com/ahmedkaludi/ads-for-wp/issues/242
