### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by utags** [ahmedkaludi/ads-for-wp#241]
After I enabled Ads for WP I can see following errors in chrome dev console. 

> (index):35 Uncaught ReferenceError: jQuery is not defined
>     at (index):35
> (anonymous) @ (index):35
> Uncaught TypeError: a(...).on is not a function              ads-front.min.js?ver=1.9.4:1 
>     at i (ads-front.min.js?ver=1.9.4:1)
>     at HTMLDocument.<anonymous> (ads-front.min.js?ver=1.9.4:1)
>     at Function.<anonymous> (jquery.min.js?ver=1.3.2:19)
>     at Function.each (jquery.min.js?ver=1.3.2:12)
>     at Function.ready (jquery.min.js?ver=1.3.2:19)
>     at HTMLDocument.<anonymous> (jquery.min.js?ver=1.3.2:19)
> i @ ads-front.min.js?ver=1.9.4:1
> (anonymous) @ ads-front.min.js?ver=1.9.4:1
> (anonymous) @ jquery.min.js?ver=1.3.2:19
> each @ jquery.min.js?ver=1.3.2:12
> ready @ jquery.min.js?ver=1.3.2:19
> (anonymous) @ jquery.min.js?ver=1.3.2:19

> Exception in queued GPT command TypeError: Cannot read property 'addService' of null  pubads_impl_2019082701.js:15 
>     at Arguments.<anonymous> ((index):50)
>     at Sk.push (pubads_impl_2019082701.js:15)
>     at Zk (pubads_impl_2019082701.js:15)
>     at pubads_impl_2019082701.js:15
>     at Pq (pubads_impl_2019082701.js:15)
>     at pubads_impl_2019082701.js:15
>     at pubads_impl_2019082701.js:15
> Sk.push @ pubads_impl_2019082701.js:15
> Zk @ pubads_impl_2019082701.js:15
> (anonymous) @ pubads_impl_2019082701.js:15
> Pq @ pubads_impl_2019082701.js:15
> (anonymous) @ pubads_impl_2019082701.js:15
> (anonymous) @ pubads_impl_2019082701.js:15

> Uncaught TypeError: a.isEmptyObject is not a function          ads-front.min.js?ver=1.9.4:1
>     at ads-front.min.js?ver=1.9.4:1
> (anonymous) @ ads-front.min.js?ver=1.9.4:1
> setTimeout (async)
> i @ ads-front.min.js?ver=1.9.4:1
> (anonymous) @ ads-front.min.js?ver=1.9.4:1
> (anonymous) @ jquery.min.js?ver=1.3.2:19
> each @ jquery.min.js?ver=1.3.2:12
> ready @ jquery.min.js?ver=1.3.2:19
> (anonymous) @ jquery.min.js?ver=1.3.2:19

**Comment by ahmedkaludi** [comment]
The Github repo is for the valid and tested issues, for technical help, kindly create a ticket on http://www.adsforwp.com/contact/
