### ISSUE TITLE
After update ads are decentralized

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#244]
Version 1.9.5 note that you are not fully responsive:
https://i.imgur.com/aQYW9a2.png

Version 1.9.3 everything works normally:
https://i.imgur.com/HkAauJ3.png

**Note from @ahmedkaludi  - THis is a valid issue, test it properly, when it is re-created then just let me know, I want to review the issue.**

https://wordpress.org/support/topic/after-update-ads-are-decentralized/#post-11919853

**Comment by ahmedkaludi** [comment]
The settings are:
Ad Type Adsense
AdSense Type Normal
Size Large Rectangle
Responsive

Alignment Center

**Comment by santosh8793** [comment]
Pushed in 1.9.6
