### ISSUE TITLE
responsive Ads with Newsmag theme

### ISSUE THREAD

**Issue by nommanshaik18** [ahmedkaludi/ads-for-wp#246]
need to test responsive Ads option with Newsmag theme

User is using the shortcode and applying in the theme ads option in header https://prnt.sc/p56y4b

Setup is in group

Ref: https://secure.helpscout.net/conversation/948558645/80416?folderId=1060556

**Comment by santosh8793** [comment]
This issue has been resolved in below ticket
Ref: https://github.com/ahmedkaludi/ads-for-wp/issues/249

**Comment by santosh8793** [comment]
Pushed in 1.9.7
