### ISSUE TITLE
AMP Transitional mode Ads not showing Between the content

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#247]
I use only the official AMP plugin. Not uses any other AMP plugin.

I use AMP plugin Transitional mode. This WordPress site uses the Genesis theme. When I use between the Content (automatic), it’s not working anymore. But if I view the page source, I can see that relevant ads. I added Ads short code to header, currently works only that short code.

REF; https://wordpress.org/support/topic/amp-transitional-mode-ads-not-showing-between-the-content/#post-11932525

**Comment by santosh8793** [comment]
This issue has been tested on localhost and it is working perfectly

**Comment by utags** [comment]
Dear @santosh8793 , 

Did you test it with Redis Object cache enabled? I faced the same issue, when I enabled the WordPress Redis object cache. I have tested it with this plugin and faced the same issue. 

https://wordpress.org/plugins/redis-cache/
