### ISSUE TITLE
amp-sticky-ad script is not generating when the content of the post is coming from the custom amp editor

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/ads-for-wp#248]
https://secure.helpscout.net/conversation/951772859/81534?folderId=2632030

The amp-sticky-ad script is not generating when the content of the post is coming from the custom amp editor

**Comment by santosh8793** [comment]
Dependent on below ticket
Ref: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/3698
