### ISSUE TITLE
Need to improve javascript functionality of adsforwp option panel

### ISSUE THREAD

**Issue by santosh8793** [ahmedkaludi/ads-for-wp#251]
![adsforwp-option-panel](https://user-images.githubusercontent.com/40556903/65374288-ed45cd00-dca5-11e9-96ab-15e960e6cb02.png)

**Comment by ahmedkaludi** [comment]
We need to improve the backend js code, to make it in the array format.

**Comment by santosh8793** [comment]
Pushed in 1.9.12
