### ISSUE TITLE
Need to add Fluid compatibility for double click ads

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/ads-for-wp#252]
User is using Double click ads and needs fluid option.

References:

Document: https://github.com/ampproject/amphtml/blob/master/extensions/amp-ad-network-doubleclick-impl/fluid.md

Ticket: https://secure.helpscout.net/conversation/963442029/85474?folderId=3126461

**Comment by santosh8793** [comment]
Pushed in 1.9.10
