### ISSUE TITLE
widgets ids are not getting loaded when we use Engage ads by placing a  shortcode or the display type options

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/ads-for-wp#257]
https://secure.helpscout.net/conversation/971881039/87768?folderId=2632030

widgets ids are not getting loaded when we use Engage ads by placing a  shortcode of it but if we put raw HTML code widgets ids are loading and ads are displaying.

Please, this screenshot: 

Coding placing: https://monosnap.com/file/t7ntSrqDT93FJxvARqaqFkmGMmUnFX

Output: https://monosnap.com/file/cTptqk8E0SUzWO6doHgQ3S8jEIFoof

Also please cross-check, is the same issue happening with other ad companies as well

**Comment by santosh8793** [comment]
Pushed in 1.9.8
