### ISSUE TITLE
Need to detect current version of mobile 

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/ads-for-wp#261]
Need to detect the current version of the mobile. Ads are not displaying as par condition applied if enable for the only tab then also its display on the desktop. User checking these ads in MacBook pro.

See this screenshot:
https://monosnap.com/file/UvQMN2ZyTv6q4QKqLSkmByfgdanVbX

You can find out a query log here:
https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/48f865ba09afe039564264a9b33b69cbb912f2f8

REF:https://secure.helpscout.net/conversation/961111377/84811?folderId=3008055

**Comment by sardarui** [comment]
They also "Need to detect current version of desktop" as the reverse situation sometimes also happens.

Sometimes on mobile you also see the desktop version

**Comment by santosh8793** [comment]
Pushed in 1.9.10
