### ISSUE TITLE
AMP Transitional mode mode Ads Not showing between paragraph with Redis Object cache.

### ISSUE THREAD

**Issue by utags** [ahmedkaludi/ads-for-wp#262]
Hi,

When I use WordPress Redis Object caching, Ads for WP plugin fail to show Adsense ad units on post content area (between paragraph) on AMP Transitional mode. This is a strange issue. Ads only visible on header section in this situation. 

Without the AMP mode again ads started to show in between paragraphs. 

Used [this Redis Object Cache plugin](https://wordpress.org/plugins/redis-cache/): https://wordpress.org/plugins/redis-cache/

**Tested environment.** 

Ubuntu 18.04 with Nginx 1.17.4 and Php7.3, MariaDB, Wordpress FastCGI cache enabled with the [official WordPress AMP plugin](https://wordpress.org/plugins/amp/).

**Comment by santosh8793** [comment]
Will you please contact us on this link https://ampforwp.com/support/, so that we can debug your issue and make sure it will be fixed as soon as possible.

**Comment by santosh8793** [comment]
Github is for tried and tested bugs.
Please create a ticket for this on https://www.adsforwp.com/contact/
once it's verified by our technical team, then we will re-open or create a bug report.

**Comment by santosh8793** [comment]
When I use WordPress Redis Object caching, Ads for WP plugin fail to show Adsense ad units on post content area (between paragraph) on AMP Transitional mode. This is a strange issue. Ads only visible on header section in this situation.
Ref: https://secure.helpscout.net/conversation/981389476/91426?folderId=3257665
