### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Rkroy** [ahmedkaludi/ads-for-wp#264]
Below debug warning displays while editing a post, the warning appears for a few seconds and then disappears.
Warning: Invalid argument supplied for foreach() in C:\.....\ads-for-wp\admin\inc\gutenberg\adsforwp-gutenberg.php on line 45

Ref: https://secure.helpscout.net/conversation/976350828/89410?folderId=2322651

**Comment by santosh8793** [comment]
Pushed in 1.9.10
