### ISSUE TITLE
Wrong error message display 

### ISSUE THREAD

**Issue by Arihantkankariya09** [ahmedkaludi/ads-for-wp#265]
The user is getting an error message like 
https://monosnap.com/file/RiKu8cTjzBs3M7tIfo1NYpU3K0z7wb

Instead, it should display "Your ads are in draft, publish it".
Helpscout link :-https://secure.helpscout.net/conversation/978145717/89975?folderId=3243584

**Comment by santosh8793** [comment]
Pushed in 1.9.10
