### ISSUE TITLE
Custom Code box gets empty after updating the Ad

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/ads-for-wp#27]
Issue created in localhost

**Comment by Sanjeevsetu** [comment]
Wordpress escaping function was escaping amp tag. Put an amp tag array into allowhtml tag. its fixed now

**Comment by ahmedkaludi** [comment]
I tried to insert this content, it still goes blank in the input feild after saving. `<amp-img src="http://1.gravatar.com/avatar/d7a973c7dab26985da5f961be7b74480?s=96&d=mm&r=g" width="223" height="34"></amp-img>`
