### ISSUE TITLE
amp-iframe not working in custom code

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#277]
`<amp-iframe
      src="https://embed.empower.net/?video=5855011e-efd8-46ab-b2f6-d6191f1ac299&player=8261f255-3039-456d-a2b4-7c8e68bb3fb7&site=30a9d67f-911c-406c-89d3-ba68ed6d7dd9&siteName=windowstechit"
      sandbox="allow-scripts allow-same-origin"
      frameborder="0"
 layout="responsive"
      height="360"
      width="640">
      <amp-img layout="fill" src="https://str.empower.net/thumbnails/5855011e-efd8-46ab-b2f6-d6191f1ac299.jpg" placeholder></amp-img>
</amp-iframe>`

and it should work with proper js files

**Comment by santosh8793** [comment]
Pushed into 1.9.13
