### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/ads-for-wp#286]
Notice: Undefined offset: 0 in D:\XAMPP\htdocs\wordpress\wp-content\plugins\ads-for-wp\output\functions.php on line 1195

Notice: Undefined offset: 0 in D:\XAMPP\htdocs\wordpress\wp-content\plugins\ads-for-wp\output\functions.php on line 1195

**Comment by santosh8793** [comment]
Pushed into 1.9.13
