### ISSUE TITLE
Tabs link error in Multisite

### ISSUE THREAD

**Issue by fnorte** [ahmedkaludi/ads-for-wp#290]
I have a multisite installation and I'm get an error every navigation into the tabs of settings page.
The link try to send to my NETWORK page.
Checking the code, in the function adsforwp_admin_link (line 641) there is a check for Multisite to make this redirect.
But I think there is not necessary (and causing this problem) because each site has your own settings.
The problem with this, I have to enter the link manually to get the tabs, and I can't import the ADs from one multisite to another (the "save" button try to send to Network page too), make me reenter every one manually.

**Comment by fnorte** [comment]
LINE 641:
`	if ( ! is_multisite() ) {
		$link = admin_url( 'admin.php?page=' . $page );
	}
	else {
		$link = network_admin_url( 'admin.php?page=' . $page );
	}`

Should be only:
`	$link = admin_url( 'admin.php?page=' . $page );`

Or check if is IN the network admin:
`	if ( ! is_network_admin() ) {
		$link = admin_url( 'admin.php?page=' . $page );
	}
	else {
		$link = network_admin_url( 'admin.php?page=' . $page );
	}`

**Comment by santosh8793** [comment]
Pushed into 1.9.14
