### ISSUE TITLE
Taxonomy terms condition for selected taxonomy type is not working after first condition

### ISSUE THREAD

**Issue by amer07** [ahmedkaludi/ads-for-wp#292]
Case-I 
https://secure.helpscout.net/conversation/992602349/95343?folderId=2770543

In advance display condition, if we select the first condition of display it will work, whereas, if we select the second condition it does not work, it does not show list dropdown.

See this screenshot: https://prnt.sc/pq4jwc

**Comment by santosh8793** [comment]
Pushed into 1.9.13
