### ISSUE TITLE
If the user add SVG image in image banner ads then need to add option to select height and width.

### ISSUE THREAD

**Issue by SayyadF** [ahmedkaludi/ads-for-wp#297]
If the user adds SVG image in image banner ads then we need to add an option to select height and width.

See this screenshot:
https://monosnap.com/file/rQWJxMOSmEexoXwzlqhln0uMiQEPaz

REL:https://secure.helpscout.net/conversation/1004043204/97557/

**Comment by santosh8793** [comment]
Pushed into 1.9.15
