### ISSUE TITLE
The percent of content option in ads between post abruptly cuts out content and causing errors on the site.

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/ads-for-wp#316]
When trying to show ads after a certain percent of content sometimes it abruptly cuts content half and causing issues. 
case1) https://secure.helpscout.net/conversation/1065904604/108206?folderId=3514643
screengrab1) https://monosnap.com/file/yrtnnmxoxjGWRuzFgqsarWLjG3QlIl
screnngrab2) https://monosnap.com/file/fWxECPPVOGe4ZqASspiTmYYsPQE1or

**Comment by santosh8793** [comment]
Pushed in to 1.9.15.3
