### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated in D:\XAMPP\htdocs\wordpress\wp-content\plugins\ads-for-wp\admin\inc\Google\Utils.php on line 67

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/ads-for-wp#321]
Deprecated: Array and string offset access syntax with curly braces is deprecated in D:\XAMPP\htdocs\wordpress\wp-content\plugins\ads-for-wp\admin\inc\Google\Utils.php on line 67

**Comment by calgarytech** [comment]
I am seeing the same thing on my WP 5.5.1 install (see below).  I have been waiting for months for this to be resolve but will be forced to remove the add-in and find another product if this is not resolved soon.

Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/urtech7/partisanissues.com/wp-content/plugins/ads-for-wp/admin/inc/Google/Utils.php on line 67

Warning: Cannot modify header information - headers already sent by (output started at /home/urtech7/partisanissues.com/wp-content/plugins/ads-for-wp/admin/inc/Google/Utils.php:67) in /home/urtech7/partisanissues.com/wp-includes/functions.php on line 6270

Warning: Cannot modify header information - headers already sent by (output started at /home/urtech7/partisanissues.com/wp-content/plugins/ads-for-wp/admin/inc/Google/Utils.php:67) in /home/urtech7/partisanissues.com/wp-admin/includes/misc.php on line 1310

Warning: Cannot modify header information - headers already sent by (output started at /home/urtech7/partisanissues.com/wp-content/plugins/ads-for-wp/admin/inc/Google/Utils.php:67) in /home/urtech7/partisanissues.com/wp-admin/admin-header.php on line 9
