### ISSUE TITLE
Unable to display ads on page build using Elementor. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/ads-for-wp#323]
User unable to display ads on a page which was built using Elementor.  Shortcode was deployed in the content, but unfortunately, the ads were not being displayed on the site.
Ref: https://www.zotezo.com/hi/connect/ling-mota-lamba-karne-ka-tarika-in-hindi/?amp

**Comment by santosh8793** [comment]
Pushed into 1.9.16
