### ISSUE TITLE
User receives an error on query monitor. 

### ISSUE THREAD

**Issue by DikshantJoshi** [ahmedkaludi/ads-for-wp#325]
The user sees SQL queries on his query monitor. 
SELECT DISTINCT YEAR( post_date ) AS year, MONTH( post_date ) AS month FROM wp_posts WHERE post_type = 'attachment' ORDER BY post_date DESC-
ref: https://secure.helpscout.net/conversation/1104726934/115896?folderId=673452.

**Comment by santosh8793** [comment]
Pushed into 1.9.16
