### ISSUE TITLE
Receiving Exception in queued GPT command TypeError in console when loading ad.

### ISSUE THREAD

**Issue by nakib4tech** [ahmedkaludi/ads-for-wp#326]
I receive the following error on Chrome Console when opening any post containing an ad unit:

**Exception in queued GPT command TypeError: Cannot read property 'addService' of null**

![11111](https://user-images.githubusercontent.com/40723843/76885315-17acc780-6890-11ea-8a97-a6f0016c92f4.PNG)

The ads still shows without issues..

I'm having trouble figuring out if its related to a bug with AdsforWP or anything else. Please offer any information you have about this error.

REF: https://nakib4tech.com/faq-rich-snippets-wordpress/

**Comment by makutaII** [comment]
same error only with AdsforWP plugin. 
REF: https://wabisabi.by/

**Comment by santosh8793** [comment]
Pushed into 1.9.16
