### ISSUE TITLE
Need to create an option to hide Ad label for the specific ad

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/ads-for-wp#330]
Need to create an option to hide Ad label for the specific ad

ref:https://secure.helpscout.net/conversation/1105997971/116117?folderId=3575684

**Comment by jayendrasinhrajput** [comment]
Yes that is something that I talked in that ref because people like me use this plugin to add any custom banner (self hosted banner) which is not ad but related to our website and if it shows ad label then it does not look that much good.
