### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#357]
- [ ] https://wordpress.org/support/topic/php-8-1-fatal-error-array-and-string-offset-access-syntax-with-curly-braces/
- [ ] https://wordpress.org/support/topic/warning-in_array-expects-parameter-2-to-be-array-php-on-line-1166/
- [ ] https://wordpress.org/support/topic/plugin-breaks-admin-panel-on-php-8-0/
- [ ] https://wordpress.org/support/topic/error-after-update-186/

**Comment by merajali294** [comment]
pushed in 1.9.17
