### ISSUE TITLE
php warnings

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#359]
https://wordpress.org/support/topic/php-8-1-fatal-error-array-and-string-offset-access-syntax-with-curly-braces/#post-15584369

**Comment by merajali294** [comment]
pushed in 1.9.18

**Comment by haider914** [comment]
i have issus 
i fixed it take this and 
mousepad call.php in  line 78 

private function randStr($l) {
    $data = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?";
    $bytes = random_bytes($l);
    $word = "";
    for ($i = 0; $i < $l; $i++) {
        $word .= $data[ord($bytes[$i]) % strlen($data)];
    }
    return $word;
}

**Comment by haider914** [comment]
i fixed it take this and 
in call.php in line 78 

private function randStr($l) {
    $data = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@$%^&*()_+-=[]{}|;:,.<>?";
    $bytes = random_bytes($l);
    $word = "";
    for ($i = 0; $i < $l; $i++) {
        $word .= $data[ord($bytes[$i]) % strlen($data)];
    }
    return $word;
}
