### ISSUE TITLE
AMP ads is not working in Ads for WP Plugin

### ISSUE THREAD

**Issue by wedlockideas** [ahmedkaludi/ads-for-wp#36]
Recently I installed Ads for WP plugin it is really nice but my concern is since you guys mentioned it is AMP compatible I added ads using the plugin Google Ads are showing in my normal between the content but in AMP page ads are not showing. 

While Creating the ad AMP Compatibility is activated. This is my website yvoffer.com Please resolve ASAP. 
Whether I can use the advertisement option in AMP plugin itself or we have to use the amp for wp plugin for AMP ads

**Comment by Sanjeevsetu** [comment]
Hi, 
Thanks for your feedback. I have solved your issue, please pull new code, If you still have any query please contact our support team. contact - team@magazine3.com

**Comment by wedlockideas** [comment]
Please, don't close I tried adding new ad code by enabling amp
compatibility but still amp ads are not coming.

yvoffer.com please check
