### ISSUE TITLE
Conflict issue with connection of Google analytics

### ISSUE THREAD

**Issue by MohammedAkramU7** [ahmedkaludi/ads-for-wp#378]
Ref ticket:- https://magazine3.in/conversation/85646?folder_id=21

Description:-
When a user tries to connect with Google Analytics it's showing error

Issue URL:-
https://monosnap.com/direct/oYq0je9yxmCMCXBlDAskbDXje4Y8no

**Comment by Sanjeevsetu** [comment]
This module has been deprecated in AdsforWP. New Ads Report will be added soon
