### ISSUE TITLE
#Add

### ISSUE THREAD

**Issue by islamneshat** [ahmedkaludi/ads-for-wp#379]

**Comment by islamneshat** [comment]
@islamneshat`<script async custom-element="amp-ad" 

- [ ] src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>`

**Comment by islamneshat** [comment]
- [ ] <script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>

**Comment by Sanjeevsetu** [comment]
What is all about this can you explain it.
