### ISSUE TITLE
Ads are not working in wp bakery

### ISSUE THREAD

**Issue by beingsmart3** [ahmedkaludi/ads-for-wp#60]
Ref:  https://secure.helpscout.net/conversation/627756952/30916?folderId=1914712

When we add the Ads shortcode in the Widgetised sidebar of  wp bakery the Ads are not displaying

**Comment by Sanjeevsetu** [comment]
There are conditional settings for every ad and group ads. Default settings for every ad and group ads is post so it will only show on post. If you want it on page as well than change settings.
