### ISSUE TITLE
PreRelease 1.0.5 Feedback

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#66]
- [x] Existing User's ads throw errors: http://take.ms/69bXg

- [x] http://take.ms/Esmvi - (1) This metabox should be called "Advanced Display Conditions"  and (2) Default should be post type. (3) the metabox position should be after "Display"  

- [x] http://take.ms/yGFx9 - (1) first dropdown needs to cover the full width. (2) Embed code is too flashy.

- [x] Popup doesn't look properly: http://take.ms/nFRl1

- [x]  http://take.ms/Ilzxg - Image AD should be called "Image Banner Ad" and custom code should always be at the end.

- [x] This text should not bold. Make it look normal like others.

- [x] View post should not be there: http://take.ms/zWRPZ5

- [x] There should be a tab called Tools, which should have the migrator tool: http://take.ms/4I6La

- [x] This feature does not display: http://take.ms/LSxe2

- [x] Support email test: http://take.ms/tziFC

- [x] Image banner Ad should be second last option: http://take.ms/gUhQO

- [x] DEBUG ERROR Warning: A non-numeric value encountered in /Applications/MAMP/htdocs/wordpress/wp-content/plugins/ads-for-wp/output/functions.php on line 50

**Comment by syedimran22** [comment]
Desc: 1)  Already existed ads are not reflecting in this version and reflecting these errors see this screenshot: https://monosnap.com/file/nDR8wITNTPorQ4tfytIXWYOk3QDAMw

2) But the new ads are reflecting without any errors see this screesnhot: https://monosnap.com/file/SsUreEV6NurTqK2e9Oxbe4Wbd7DBda
