### ISSUE TITLE
1.0.5 Pre-Release Review

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/ads-for-wp#78]
- [x] Remove Add New ads and it should be located here: http://take.ms/JMRUB

- [x] The sequence of the pages should be [Ads, Groups, Analytics, Settings]

- [x] Unnessesary Gap: http://take.ms/HzZhk

- [x] Ads should display in the bottom: http://take.ms/TTF6p

- [x] After activation, it should redirect to Ads Post type page

- [x] If there is no ads, then it should have a text and a button TEXT: Welcome to Ads for WP. It looks like you don't have any ads, BUTTON: Let's create a new Ad - upon clicking, it should create a new ad

- [x] Ad performance Title 

- [x] if there's no data available in the pie chart, then it shoud say "Not enough data at the moment, Please check back soon"

- [x] Mobile, desktop & AMP - Data comparision - the one which shows with percentage.

- [x] Debug errors

- [x] http://take.ms/si4Nw - 1. Title should be: Ads for WP Settings 2. labels should be clickable 

- [ ]

**Comment by Rkroy** [comment]
- [ ] If we select Where to display as between the content and show globally in Advanced display conditions where all posts are active, Ads are not displaying in home page.
