### ISSUE TITLE
when i install this extension ads for wp this error occurs

### ISSUE THREAD

**Issue by syedarslan619** [ahmedkaludi/ads-for-wp#91]
Warning: require(/home/trevdleg/getspecification.com/wp-content/plugins/ads-for-wp//admin/inc/analytics-settings.php): failed to open stream: No such file or directory in /home/trevdleg/getspecification.com/wp-content/plugins/ads-for-wp/ads-for-wp.php on line 31

Fatal error: require(): Failed opening required '/home/trevdleg/getspecification.com/wp-content/plugins/ads-for-wp//admin/inc/analytics-settings.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/trevdleg/getspecification.com/wp-content/plugins/ads-for-wp/ads-for-wp.php on line 31

**Comment by Sanjeevsetu** [comment]
Hi, 
It is working fine for other users. Could you please cantact us at team@magazine3.com so that we can help you.

**Comment by jorgepa77** [comment]
I have the same error

**Comment by Sanjeevsetu** [comment]
@syedarslan619 
From where you have downloaded the plugin? Error is showing the main php file is missing. Please download our latest version from https://wordpress.org/plugins/ads-for-wp/. You still have errors. Please feel free to write us at team@magazine3.com. We will be happy to help you. Thank you so much.

**Comment by ahmedkaludi** [comment]
@jorgepa77 @syedarslan619 Are you still having the same issue?

**Comment by ahmedkaludi** [comment]
closed due to inactivity.
