### ISSUE TITLE
When the users is choosing  ad visibility  to 'hide' for non-amp posts then it is working for new posts only.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/ads-for-wp#92]
Desc:  I need the amp ads not to show on the regular pages. I set the ad visibility in the plugin to 'hide', and that works on posts that I'm publishing now. But on previously published posts (there are thousands) it seems to default to 'show'.

Ref: https://secure.helpscout.net/conversation/651657183/32847?folderId=2169248

**Comment by Sanjeevsetu** [comment]
We have set default to show ads on all posts either it is old or new.
